### ISSUE TITLE
Error when running bash exp/hoi_classifier/scripts/train.sh

### ISSUE THREAD

**Issue by yojayc** [BigRedT/no_frills_hoi_det#15]
The following aguments were specified:
--------------------------------------------------------------------------------
--fp_to_tp_ratio                                  1000
--imgs_per_batch                                  1
--rcnn_det_prob                                   True
--verb_given_appearance                           True
--verb_given_boxes_and_object_label               True
--verb_given_human_appearance                     False
--verb_given_human_pose                           True
--verb_given_object_appearance                    False
Saving exp constants ...
Saving data_train constants ...
Saving data_val constants ...
Saving model constants ...
Creating model ...
Writing model.txt ...
Creating data loaders ...
Traceback (most recent call last):
  File "/data/cuiyujie/xuyuxiao/anaconda2/envs/pytorch030/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/data/cuiyujie/xuyuxiao/anaconda2/envs/pytorch030/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/cuiyujie/no_frills_hoi_det/exp/hoi_classifier/run.py", line 356, in <module>
    list_exps(globals())
  File "/data/cuiyujie/no_frills_hoi_det/exp/experimenter.py", line 16, in list_exps
    module_globals[args.exp]()
  File "/data/cuiyujie/no_frills_hoi_det/exp/hoi_classifier/run.py", line 235, in exp_train
    train.main(exp_const,data_const_train,data_const_val,model_const)
  File "/data/cuiyujie/no_frills_hoi_det/exp/hoi_classifier/train.py", line 173, in main
    train_model(model,dataset_train,dataset_val,exp_const)
  File "/data/cuiyujie/no_frills_hoi_det/exp/hoi_classifier/train.py", line 49, in train_model
    prob_vec, factor_scores = model.hoi_classifier(feats)
  File "/data/cuiyujie/xuyuxiao/anaconda2/envs/pytorch030/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/cuiyujie/no_frills_hoi_det/exp/hoi_classifier/models/hoi_classifier_model.py", line 102, in forward
    temp_m = module(feats)
  File "/data/cuiyujie/xuyuxiao/anaconda2/envs/pytorch030/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/cuiyujie/no_frills_hoi_det/exp/hoi_classifier/models/verb_given_human_pose.py", line 65, in forward
    w.write("self.mlp({}):{}\n".format(in_feat, self.mlp(in_feat)))
  File "/data/cuiyujie/xuyuxiao/anaconda2/envs/pytorch030/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/cuiyujie/no_frills_hoi_det/utils/pytorch_layers.py", line 102, in forward
    w.write("x:{}\nlayer(x):{}\n\n".format(x, layer(x)))
  File "/data/cuiyujie/xuyuxiao/anaconda2/envs/pytorch030/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/cuiyujie/xuyuxiao/anaconda2/envs/pytorch030/lib/python3.6/site-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/data/cuiyujie/xuyuxiao/anaconda2/envs/pytorch030/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/cuiyujie/xuyuxiao/anaconda2/envs/pytorch030/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 55, in forward
    return F.linear(input, self.weight, self.bias)
  File "/data/cuiyujie/xuyuxiao/anaconda2/envs/pytorch030/lib/python3.6/site-packages/torch/nn/functional.py", line 835, in linear
    return torch.addmm(bias, input, weight.t())
RuntimeError: size mismatch at /pytorch/torch/lib/THC/generic/THCTensorMathBlas.cu:247
(pytorch030) cuiyujie@amax:/data/cuiyujie/no_frills_hoi_det$ bash exp/hoi_classifier/scripts/train.sh 7
/data/cuiyujie/xuyuxiao/anaconda2/envs/pytorch030/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
--------------------------------------------------------------------------------
The following aguments were specified:
--------------------------------------------------------------------------------
--fp_to_tp_ratio                                  1000
--imgs_per_batch                                  1
--rcnn_det_prob                                   True
--verb_given_appearance                           True
--verb_given_boxes_and_object_label               True
--verb_given_human_appearance                     False
--verb_given_human_pose                           True
--verb_given_object_appearance                    False
Saving exp constants ...
Saving data_train constants ...
Saving data_val constants ...
Saving model constants ...
Creating model ...
Writing model.txt ...
Creating data loaders ...
Traceback (most recent call last):
  File "/data/cuiyujie/xuyuxiao/anaconda2/envs/pytorch030/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/data/cuiyujie/xuyuxiao/anaconda2/envs/pytorch030/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/cuiyujie/no_frills_hoi_det/exp/hoi_classifier/run.py", line 356, in <module>
    list_exps(globals())
  File "/data/cuiyujie/no_frills_hoi_det/exp/experimenter.py", line 16, in list_exps
    module_globals[args.exp]()
  File "/data/cuiyujie/no_frills_hoi_det/exp/hoi_classifier/run.py", line 235, in exp_train
    train.main(exp_const,data_const_train,data_const_val,model_const)
  File "/data/cuiyujie/no_frills_hoi_det/exp/hoi_classifier/train.py", line 173, in main
    train_model(model,dataset_train,dataset_val,exp_const)
  File "/data/cuiyujie/no_frills_hoi_det/exp/hoi_classifier/train.py", line 49, in train_model
    prob_vec, factor_scores = model.hoi_classifier(feats)
  File "/data/cuiyujie/xuyuxiao/anaconda2/envs/pytorch030/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/cuiyujie/no_frills_hoi_det/exp/hoi_classifier/models/hoi_classifier_model.py", line 110, in forward
    factor_scores[factor_name] = module(feats)
  File "/data/cuiyujie/xuyuxiao/anaconda2/envs/pytorch030/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/cuiyujie/no_frills_hoi_det/exp/hoi_classifier/models/verb_given_human_pose.py", line 67, in forward
    factor_scores = self.mlp(in_feat)
  File "/data/cuiyujie/xuyuxiao/anaconda2/envs/pytorch030/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/cuiyujie/no_frills_hoi_det/utils/pytorch_layers.py", line 107, in forward
    x = layer(x)
  File "/data/cuiyujie/xuyuxiao/anaconda2/envs/pytorch030/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/cuiyujie/xuyuxiao/anaconda2/envs/pytorch030/lib/python3.6/site-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/data/cuiyujie/xuyuxiao/anaconda2/envs/pytorch030/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/cuiyujie/xuyuxiao/anaconda2/envs/pytorch030/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 55, in forward
    return F.linear(input, self.weight, self.bias)
  File "/data/cuiyujie/xuyuxiao/anaconda2/envs/pytorch030/lib/python3.6/site-packages/torch/nn/functional.py", line 835, in linear
    return torch.addmm(bias, input, weight.t())
RuntimeError: size mismatch at /pytorch/torch/lib/THC/generic/THCTensorMathBlas.cu:247

When executing command "bash exp/hoi_classifier/scripts/train.sh 7", it shows the above error.
Is there something wrong with the network size?

**Comment by yojayc** [comment]
Because the in_features in MLP are 368, but the in_feat's size is \*x480 (\* means different size, e.g. 3003, 2002), which is not match to MLP, so the problem can be solved by resizing in_feat.data from \*x480 to \*x368 in verb_given_human_pose.py
