### ISSUE TITLE
Error when running bash exp/hoi_classifier/scripts/train.sh 

### ISSUE THREAD

**Issue by MathiasHaudgaard** [BigRedT/no_frills_hoi_det#2]
`Traceback (most recent call last):
  File "/home/mathias/miniconda/envs/no_fills/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/mathias/miniconda/envs/no_fills/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mathias/no_frills_hoi_det/exp/hoi_classifier/run.py", line 355, in <module>
    list_exps(globals())
  File "/home/mathias/no_frills_hoi_det/exp/experimenter.py", line 16, in list_exps
    module_globals[args.exp]()
  File "/home/mathias/no_frills_hoi_det/exp/hoi_classifier/run.py", line 234, in exp_train
    train.main(exp_const,data_const_train,data_const_val,model_const)
  File "/home/mathias/no_frills_hoi_det/exp/hoi_classifier/train.py", line 173, in main
    train_model(model,dataset_train,dataset_val,exp_const)
  File "/home/mathias/no_frills_hoi_det/exp/hoi_classifier/train.py", line 60, in train_model
    max_prob = hoi_prob.max().data[0]
IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number`

getting this error when running exp/hoi_classifier/scripts/train.sh. Not sure if I should use tensor.item() to fix it or if there is another fix.

**Comment by BigRedT** [comment]
The code uses pytorch 0.3.1. Several breaking changes were introduced in later versions (>0.4). Scalar tensors were one of them.

You could try to migrate the code to work with newer versions of pytorch by following [https://pytorch.org/blog/pytorch-0_4_0-migration-guide/](https://pytorch.org/blog/pytorch-0_4_0-migration-guide/). 

But it might be easier to just use 0.3.1 :)

**Comment by MathiasHaudgaard** [comment]
Thanks!
